// Auto-generated by generate-field-config.mjs — do not edit manually.
// Regenerate:  node js/games/fifa-masters/generate-field-config.mjs
//
// ═══════════════════════════════════════════════════════════════════════════════
// STATIC FIELD CONFIGURATION
// ═══════════════════════════════════════════════════════════════════════════════
//
// These values are constant across every game round — they do NOT depend on
// the seed.  They describe the physical layout of the football field and the
// visual dimensions of sprites.
//
// ── Coordinate system ───────────────────────────────────────────────────────
//
//   • x-axis (horizontal):  0 = left edge of field, fieldWidth = right edge.
//     The field center is at fieldWidth / 2 = 13550.
//     Goal A (left) and Goal B (right) are positioned symmetrically around center.
//
//   • y-axis (vertical / altitude):  0 = ground level.
//     Positive y = upward.  Bonuses float between minMultiplierHeight and
//     maxMultiplierHeight.  Players stand at playerBaseHeight; the ball is
//     received/shot from playerPointLowHeight or playerPointHighHeight
//     depending on the shot distance.
//
// ── Field layout (left → right) ─────────────────────────────────────────────
//
//   Goal A ─ KA ─ [players...] ─ center ─ [players...] ─ KB ─ Goal B
//   x=1390                       x=13550                       x=25710
//
//   Team A kicks right (toward Goal B).
//   Team B kicks left  (toward Goal A).
//   Goal B goal = win,  Goal A goal = crash  (for the player/bettor).
//   Goal B save = crash, Goal A save = win.
//
// ── Property reference ──────────────────────────────────────────────────────
//
//   fieldWidth              Total horizontal extent of the field (world units).
//
//   goalposts.a.x           x-position of the LEFT goalpost (Goal A).
//   goalposts.b.x           x-position of the RIGHT goalpost (Goal B).
//   goalpostHeight          Visual height of the goalpost sprite (world units).
//
//   players[]               12 field players (6 per team), ordered left→right.
//     .x                    Absolute x-position on the field.
//     .team                 'A' or 'B'.
//                           Index in this array is the player's ID used by
//                           stops[].index to reference which player the ball
//                           visits.
//
//   playerPointLowHeight    y at which the ball is received/shot for LONG passes
//                           (horizontal distance > 7000 world units).
//   playerPointHighHeight   y at which the ball is received/shot for SHORT passes
//                           (horizontal distance ≤ 7000 world units).
//   teamBHeightOffset       Extra y added to Team B player receive/shoot heights.
//
//   maxMultiplierHeight     Upper y-bound of the bonus spawn band.
//   minMultiplierHeight     Lower y-bound of the bonus spawn band.
//
//   playerModelHeight       Sprite height of a player (visual only).
//   playerModelWidth        Sprite width of a player (visual only).
//   playerBaseHeight        y-offset of a player sprite above ground (visual only).
//   ballModelDiameter       Diameter of the ball sprite (visual only).
//
// ═══════════════════════════════════════════════════════════════════════════════

export const fieldConfig = {
  "fieldWidth": 27100,
  "goalposts": {
    "a": {
      "x": 1390
    },
    "b": {
      "x": 25710
    }
  },
  "goalpostHeight": 2230,
  "players": [
    {
      "x": 3720,
      "team": "A"
    },
    {
      "x": 5320,
      "team": "B"
    },
    {
      "x": 7780,
      "team": "A"
    },
    {
      "x": 7920,
      "team": "B"
    },
    {
      "x": 10060,
      "team": "B"
    },
    {
      "x": 12610,
      "team": "A"
    },
    {
      "x": 14490,
      "team": "B"
    },
    {
      "x": 17490,
      "team": "A"
    },
    {
      "x": 19180,
      "team": "A"
    },
    {
      "x": 19320,
      "team": "B"
    },
    {
      "x": 21780,
      "team": "A"
    },
    {
      "x": 23380,
      "team": "B"
    }
  ],
  "playerPointLowHeight": 420,
  "playerPointHighHeight": 1950,
  "teamBHeightOffset": 60,
  "maxMultiplierHeight": 4100,
  "minMultiplierHeight": 2450,
  "playerModelHeight": 1350,
  "playerModelWidth": 770,
  "playerBaseHeight": 240,
  "ballModelDiameter": 520
};
